#use python 3.11 base image
FROM python:3.11-slim

#set working directory
WORKDIR /app

#copy require and install dependencies
COPY require.txt .
RUN pip install --no-cache-dir -r require.txt

#copy rest of application code
COPY . .

#EXPOSE THE application port
EXPOSE 8000

#command to start FastAPI application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
